[package]
name = "rsynth"
version = "0.1.0"
authors = ["Alexander Lozada <alexanderpaullozada@gmail.com>"]

[dependencies]
vst2 = { git = "https://github.com/rust-dsp/rust-vst" }
asprim = "0.1"
num-traits = "0.1"
num = "0.1"
clippy = {version = "*", optional = true}

[dev-dependencies]
rand = "0.3"

[features]
default = []

[[example]]
name = "test_synth"
crate-type = ["cdylib"]