[package]
name = "rsynth"
version = "0.0.1"
authors = ["Alexander Lozada <alexanderpaullozada@gmail.com>"]
description = "An easier way to create VST synths."
license = "BSD-3-Clause"
autoexamples = false

[features]
jack-backend=["jack"]

[dependencies]
vst = "0.0.2"
asprim = "0.1"
num-traits = "0.1"
num = "0.1"
jack = {version = "0.6.0", optional = true}
wmidi = "1.1.0"
log = "0.4"

[patch.crates-io]
vst = {git = "https://github.com/PieterPenninckx/rust-vst.git"}


[dev-dependencies]
rand = "0.3"
simplelog = "^0.5.0"
jack = "0.6.0"



[[example]]
name = "vst_synth"
crate-type = ["cdylib"]

[[example]]
name = "jack_synth"