[package]
name = "rsynth"
version = "0.1.0"
authors = ["Alexander Lozada <alexanderpaullozada@gmail.com>"]

[dependencies]
vst = "0.1"
asprim = "0.1"
num-traits = "0.1"
num = "0.1"

[dev-dependencies]
rand = "0.3"

[[example]]
name = "test_synth"
crate-type = ["cdylib"]
