[package]
name = "rsynth"
version = "0.0.1"
authors = ["Alexander Lozada <alexanderpaullozada@gmail.com>", "Pieter Penninckx"]
description = "A library for developing audio plugins and applications, with a focus on software synthesis."
license = "BSD-3-Clause"
autoexamples = false
edition = "2018"

[features]
backend-jack = ["jack"]
backend-vst = ["vst"]
backend-file-all = ["backend-file-hound"]
backend-file-hound = ["hound", "backend-file", "sample"]
backend-file-rimd = ["rimd", "backend-file"]
backend-file = []

[dependencies]
asprim = "0.1"
num-traits = "0.1"
log = "0.4"
doc-comment = "0.3.1"
jack = {version = "0.6.0", optional = true}
vst = {version = "0.1.0", optional = true}
hound = {version = "3.4.0", optional = true}
sample = {version = "0.10.0", optional = true}
rimd = {git = "https://github.com/RustAudio/rimd.git", optional = true}

[dev-dependencies]
rand = "0.3"

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "vst_synth"
crate-type = ["cdylib"]

[[example]]
name = "jack_synth"
