[package]
name = "rsynth"
version = "0.0.1"
authors = ["Alexander Lozada <alexanderpaullozada@gmail.com>"]
description = "An easier way to create VST synths."
license = "BSD-3-Clause"

[features]
jack-backend=["jack"]

[dependencies]
vst = "0.0.1"
asprim = "0.1"
num-traits = "0.1"
num = "0.1"
jack = {version = "0.6.0", optional = true}


[dev-dependencies]
rand = "0.3"

[[example]]
name = "test_synth"
crate-type = ["cdylib"]
