[package]
name = "rsynth"
version = "0.0.1"
authors = ["Alexander Lozada <alexanderpaullozada@gmail.com>"]
description = "An easier way to create VST synths."
license = "BSD-3-Clause"
autoexamples = false
edition = "2018"

[features]
default=["stable"]
jack-backend=["jack"]
stable=["syllogism", "syllogism-macro"]

[dependencies]
vst = "0.0.2"
asprim = "0.1"
num-traits = "0.1"
num = "0.1"
jack = {version = "0.6.0", optional = true}
log = "0.4"
syllogism = {version = "0.1", optional = true}       # See also under dev-dependencies.
syllogism-macro = {version = "0.1", optional = true} # See also under dev-dependencies.

[dev-dependencies]
rand = "0.3"
simplelog = "^0.5.0"
jack = "0.6.0"
syllogism = "0.1"       # See also under dependencies.
syllogism-macro = "0.1" # See also under dependencies.



[[example]]
name = "vst_synth"
crate-type = ["cdylib"]

[[example]]
name = "jack_synth"