(function() {var implementors = {};
implementors["rsynth"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rsynth/envelope/struct.EnvelopeIteratorItem.html\" title=\"struct rsynth::envelope::EnvelopeIteratorItem\">EnvelopeIteratorItem</a>&lt;T&gt;",synthetic:false,types:["rsynth::envelope::EnvelopeIteratorItem"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rsynth/event/struct.SysExEvent.html\" title=\"struct rsynth::event::SysExEvent\">SysExEvent</a>&lt;'a&gt;",synthetic:false,types:["rsynth::event::SysExEvent"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rsynth/event/struct.RawMidiEvent.html\" title=\"struct rsynth::event::RawMidiEvent\">RawMidiEvent</a>",synthetic:false,types:["rsynth::event::RawMidiEvent"]},{text:"impl&lt;E&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"rsynth/event/struct.Timed.html\" title=\"struct rsynth::event::Timed\">Timed</a>&lt;E&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;E: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a>,&nbsp;</span>",synthetic:false,types:["rsynth::event::Timed"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"rsynth/middleware/polyphony/enum.EventType.html\" title=\"enum rsynth::middleware::polyphony::EventType\">EventType</a>",synthetic:false,types:["rsynth::middleware::polyphony::EventType"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
