name: Rust

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install libjack-dev
      run: sudo apt-get install libjack-dev
    - name: Build
      run: cargo build --verbose --features all
    - name: Run tests
      run: cargo test --verbose --features all
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: Check jack 0.6.2
      run: cargo update -p jack --precise 0.6.2; cargo check --tests --examples --features backend-jack
    - name: Check jack 0.7.0
      run: cargo update -p jack --precise 0.7.0; cargo check --tests --examples --features backend-jack
    - name: Check vst
      run: cargo check --tests --examples --features backend-vst
    - name: Check hound
      run: cargo check --tests --examples --features backend-combined-hound
    - name: Check wav
      run: cargo check --tests --examples --features backend-combined-wav
    - name: Check midly
      run: cargo check --tests --examples --features backend-combined-midly
      
