name: Rust

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Check formatting
      run: cargo fmt --all -- --check
    - name: install libjack-dev
      run: sudo apt-get install libjack-dev
    - name: Build
      run: cargo build --verbose --all-features
    - name: Run tests
      run: cargo test --verbose --all-features
    - name: Check rsor
      run: cargo check --tests --examples --features rsor-0-1
    - name: Check jack
      run: cargo check --tests --examples --features backend-jack
    - name: Check hound
      run: cargo check --tests --examples --features backend-combined-hound
    - name: Check wav 0.6
      run: cargo check --tests --examples --features backend-combined-wav-0-6
    - name: Check midly
      run: cargo check --tests --examples --features backend-combined-midly-0-5

