name: Update-gh-pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        persist-credentials: false
    - name: Rustdoc
      run: cargo rustdoc --features all
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.PUBLISH_GH_PAGES }}
        BRANCH: gh-pages
        FOLDER: target/doc
